name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    # Create a new release and get the upload URL
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.M_GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release 1.0.0
        body: |
          This is the first release of the project.
        draft: false
        prerelease: false
    
    # Generate asset files
    - name: Generate Asset File 1
      run: python3 script/main.py
      env:
        VERSION_CODE: ${{ github.sha }}
    - name: Upload Asset File 1
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.M_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./script/易混字训练集.apkg # Replace with the path to your asset file 1
        asset_name: 易混字训练集.apkg # Replace with the name of your asset file 
    - name: Upload Asset File 2
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.M_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./script/易混字测试集.apkg # Replace with the path to your asset file 1
        asset_name: 易混字测试集.apkg # Replace with the name of your asset file 