name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    # Create a new release and get the upload URL
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.M_GITHUB_TOKEN }}
        ACTIONS_STEP_DEBUG: true
      with:
        tag_name: v1.0.1
        release_name: Release 1.0.1
        draft: false
        prerelease: false
    
    # Generate asset files
    - name: Generate Asset File
      run: python3 script/main.py && ls
      env:
        VERSION_CODE: ${{ github.sha }}
        
    - name: upload build to github
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.M_GITHUB_TOKEN }}
      with:
        files: |
            data/trainset.apkg
            data/testset.apkg
        draft: false
        prerelease: false
